### ISSUE TITLE
Develops master - slave synchronization 

### ISSUE THREAD

**Issue by atuleu** [formicidae-tracker/leto#3]

**Comment by atuleu** [comment]
@matthiasruegg : after checking the data produced, there are still a timung issue. The stream reporst wrong timestamp (but actual time are alright) between the computers. Indeed the framegrabber timestamp are not synchronized between framegrabber (the framenumber are). The tool should take that into account otherwise the timing in the resulting tracking file are completely wrong.

**Comment by matthiasruegg** [comment]
By tool you mean my tool, when I read out the tracking data in real time? In the current state, is fort-studio capable to rearrange the frames according to the frame numbers and assign some consistent timestamp?

**Comment by atuleu** [comment]
I mean, its an issue in leto. No myrmidon is assuming that within each tracling data dir and hermes file, the file presents a stream of sequential frame. and does not do reordering of any kind. The ordering of frame in multiple computer tracking (for the same camera, in master/slave configuration) have to be performed at the leto level. It is mandatory as it is leto that give you a stream of realtime frame on the local network using the hermes protocol.

The reordering of frame from framenumber works fine and is well tested. The issue is that the framegrabber only shares the framenumber, but they use their own timestamp. In an hermes file you have two timestamp, one is from the OS (`Time` field), and is imprecise, the other is from the camera, which is more precise (`Timestamp`. Within an hermes file, this is the last one that will be used for computing time difference. 

The issue is that now, in a master/slave configuration, two different `Timestamp` will be mixed within one tracking file, and the timing will be wrongly reported. The way to correct this, is in leto to ask to use the `Time` field between result from different computer, to compute the real `Timestamp` offset between two computers, and correct the `Timestamp` field between computer as it produces the stream of frame. This way the stream will be correct for both the files and the realtime stream.

**Comment by atuleu** [comment]
I forgot to mention: In single computer per camera configuration everything is fine and the stream of frames are consistent in frame number `Time` and `Timestamp`.

**Comment by atuleu** [comment]
Working on v0.3.0
